### ISSUE TITLE
Help needed: Implementation of slim-redux-react tests

### ISSUE THREAD

**Issue by aGuyNamedJonas** [aGuyNamedJonas/slim-redux-react#13]
Hey Josh,
Thanks for taking care of this! Please don't be spooked by the following wall of text, I'm trying to give you the best hand-over I can only using text and not being sure how much still needs explanation. 

If you have any questions, don't hesitate to hit me up on discord!

Thanks again,
Jonas

## Current situation
* Test environment using jest is setup for slim-redux-react
* Tests can be run in watch mode (will auto-reload on file changes) using `npm run test:watch` 
* There is some initial test code for `connect()` which is mostly stubs though that still need to be implemented
* Tests for NPM module (which checks for the imports) is missing `createSlimReduxStore()`

## What needs to be done
* `connect()` needs to be covered by tests
* All the wrapper functions for `slim-redux` wrappers need to be covered by tests:
    - `subscription()`
    - `calculation()` 
    - `changeTrigger()`
    - `asyncChangeTrigger()` 

## Stuff that's important to know for this issue
* The tests for `slim-redux-react` should have a similar scope and structure as the `slim-redux` tests (find those here: [link](https://github.com/aGuyNamedJonas/slim-redux/tree/0.2-release/src/__tests__))

* The tests are sort of integration tests. They test the functionality we expect from them:  
**Example 1:** subscription() - locally passed in store preferred over global store instance [link](https://github.com/aGuyNamedJonas/slim-redux/blob/0.2-release/src/__tests__/subscription.js#L135). 
**Example 2:** subscription() - throws exception when more than three arguments are provided [link](https://github.com/aGuyNamedJonas/slim-redux/blob/0.2-release/src/__tests__/subscription.js#L94)

* The `slim-redux-react` wrapper functions have similar signatures as the `slim-redux` functions **slim-redux**: `function subscription(subscription, changeCallback, storeArg)` [link](https://github.com/aGuyNamedJonas/slim-redux/blob/0.2-release/src/subscription.js#L5),  
**slim-redux-react**: `function subscription(subscription)` [link](https://github.com/aGuyNamedJonas/slim-redux-react/blob/0.2-release/src/subscription.js)  
➡️ A lot of the tests that make sure input parameter validation is done can be re-used

* While in watch mode in jest, pressing "p" will bring up the filter menu with which individual tests can be run ➡️ very fast!

* The tests have generally three sections:  
**regular / default cases**  [link](https://github.com/aGuyNamedJonas/slim-redux/blob/0.2-release/src/__tests__/subscription.js#L10). 
**error cases** [link](https://github.com/aGuyNamedJonas/slim-redux/blob/0.2-release/src/__tests__/subscription.js#L93). 
**bug fixes** [link](https://github.com/aGuyNamedJonas/slim-redux/blob/0.2-release/src/__tests__/subscription.js#L154)

* Take a look at the tests for `changeTrigger()`: [link](https://github.com/aGuyNamedJonas/slim-redux/blob/0.2-release/src/__tests__/changeTrigger.js) They not only contain tests for the API function `changeTrigger()` but also for the change trigger function that gets returned. Might be relevant for the tests in `connect()`

## Todos
- [ ] NPM test still needs to test for the `createSlimReduxStore()` export
- [ ] Implement tests for `subscription()`
- [ ] Implement tests for `calculation()` 
- [ ] Implement tests for `changeTrigger()`
- [ ] Implement tests for `asyncChangeTrigger()`
